Repository atomist/sdm-local, pull requests merged in 2018-09, with the labels that each got.

#170 Error reporting
  lib/sdm/binding/project/ExpandedTreeMappedParameterResolver.ts
  lib/sdm/configuration/support/NotifyOnCompletionAutomationEventListener.ts
  lib/sdm/ui/HttpMessageListener.ts
  package-lock.json
  package.json
Labels: changelog:changed

#196 Run atomist in foreground in git hooks
  lib/cli/setup/addGitHooks.ts
  test/cli/setup/addGitHooks.test.ts
Labels: auto-merge:on-approve, changelog:changed

#197 Improve directory path comparisons
  lib/cli/entry/argsToGitHookInvocation.ts
  lib/cli/invocation/git/runOnGitHook.ts
  lib/cli/setup/addGitHooks.ts
  lib/common/git/handlePushBasedEventOnRepo.ts
  lib/sdm/binding/project/expandedTreeUtils.ts
  package-lock.json
  package.json
  test/cli/entry/argsToGitHookInvocation.test.ts
  test/cli/setup/addGitHooks.test.ts
  test/sdm/binding/project/expandedTreeUtils.test.ts
  tsconfig.json
Labels: auto-merge:on-approve, changelog:fixed
