Repository atomist/sdm-local, pull requests merged in 2018-08, with the labels that each got.

#89 Cleanup team -> workspace
  src/cli/embedded/embeddedMachine.ts
  src/cli/entry/argsToGitHookInvocation.ts
  src/cli/invocation/command/addCommandsByName.ts
  src/cli/invocation/command/addIntentsAsCommands.ts
  src/cli/invocation/command/addLocalSdmCommands.ts
  src/cli/invocation/command/addTriggerCommand.ts
  src/cli/invocation/command/support/embeddedCommandExecution.ts
  src/cli/invocation/git/handleGitHookEvent.ts
  src/cli/invocation/git/runOnGitHook.ts
  src/cli/invocation/git/triggerGitEvents.ts
  src/cli/invocation/http/AutomationClientConnectionConfig.ts
  src/cli/invocation/http/fetchMetadataFromAutomationClient.ts
  src/cli/invocation/http/invokeCommandHandlerUsingHttp.ts
  src/cli/invocation/http/invokeEventHandlerUsingHttp.ts
  src/common/binding/EnvConfigWorkspaceContextResolver.ts
  src/common/binding/EnvironmentTeamContextResolver.ts
  src/common/binding/WorkspaceContextResolver.ts
  src/common/binding/defaultWorkspaceContextResolver.ts
  src/common/git/handlePushBasedEventOnRepo.ts
  src/common/git/pushFromLastCommit.ts
  src/common/invocation/InvocationTarget.ts
  src/common/invocation/LocalWorkspaceContext.ts
  src/sdm/binding/event/repoOnboardingEvents.ts
  src/sdm/binding/message/HttpClientMessageClient.ts
  src/sdm/binding/project/ExpandedTreeMappedParameterResolver.ts
  src/sdm/binding/project/fileSystemProjectPersister.ts
  src/sdm/configuration/createSdmOptions.ts
  src/sdm/configuration/localPostProcessor.ts
  src/sdm/configuration/localSdmConfig.ts
  src/sdm/invocation/invokeCommandHandlerInProcess.ts
  src/sdm/invocation/invokeEventHandlerInProcess.ts
  src/sdm/ui/localLifecycle.ts
Labels: changelog:changed

#119 Migrate to atomist git-hook, fix bugs
  src/cli/entry/argsToGitHookInvocation.ts
  src/cli/invocation/git/handleGitHookEvent.ts
  src/cli/setup/addGitHooks.ts
  test/cli/entry/argsToGitHookInvocation.test.ts
  test/cli/setup/addGitHooks.test.ts
Labels: atomist:merge-on-approve, changelog:changed

#120 Update dependencies, downgrade JavaScript
  package-lock.json
  package.json
  tsconfig.json
Labels: atomist:merge-on-approve, changelog:changed

#141 Render markdown channels, timestamp and message separately
  src/sdm/ui/ConsoleMessageClient.ts
  test/cli/ui/ConsoleMessageClient.test.ts
Labels: auto-merge:on-approve

#145 Update postInstall.md
  docs/postInstall.md
Labels: auto-merge:on-approve

#157 Fix architecture picture and atomist.com link
  README.md
Labels: auto-merge:on-approve, changelog:fixed

#161 Consistently use local configuration; read hostname from configuration
  index.ts
  package-lock.json
  package.json
  src/cli/AutomationClientInfo.ts
  src/cli/embedded/embeddedMachine.ts
  src/cli/invocation/command/addCloneCommand.ts
  src/cli/invocation/command/addGitHubImportCommand.ts
  src/cli/invocation/command/addStartSdmDeliveryMachine.ts
  src/cli/invocation/command/support/runCommandOnColocatedAutomationClient.ts
  src/cli/invocation/git/handleGitHookEvent.ts
  src/cli/invocation/http/fetchMetadataFromAutomationClient.ts
  src/cli/invocation/http/support/PortRangeAutomationClientFinder.ts
  src/cli/invocation/http/support/SingleDefaultAutomationClientFinder.ts
  src/common/configuration/defaultLocalModeConfiguration.ts
  src/common/git/handlePushBasedEventOnRepo.ts
  src/common/ui/httpMessaging.ts
  src/common/util/http/LocalHostUrlAliaser.ts
  src/common/util/http/defaultLocalHostUrlAliaser.ts
  src/pack/sdm-cd/support/LocalSdmDeliveryGoal.ts
  src/pack/sdm-cd/support/SdmDeliveryOptions.ts
  src/sdm/binding/log/SimpleNodeLoggerProgressLog.ts
  src/sdm/binding/project/FileSystemProjectLoader.ts
  src/sdm/binding/project/fileSystemProjectPersister.ts
  src/sdm/configuration/configureLocal.ts
  src/sdm/configuration/createSdmOptions.ts
  src/sdm/configuration/defaultLocalSoftwareDeliveryMachineConfiguration.ts
  src/sdm/ui/HttpMessageListener.ts
  src/sdm/ui/localLifecycle.ts
  src/sdm/util/currentMachineAddress.ts
  src/typings/index.ts
  test/cli/ui/ConsoleMessageClient.test.ts
Labels: auto-merge:on-approve, changelog:changed

#163 Add additional _experimental_ view for goals with `atomist feed --goals`
  package-lock.json
  package.json
  src/cli/invocation/command/addFeedCommand.ts
  src/common/ui/httpMessaging.ts
  src/sdm/binding/message/HttpClientMessageClient.ts
  src/sdm/ui/ConsoleGoalRendering.ts
  src/sdm/ui/HttpMessageListener.ts
  src/sdm/ui/localLifecycle.ts
  src/sdm/ui/progressBar.d.ts
  src/sdm/ui/progressBar.js
Labels: changelog:added, enhancement

#167 Allow to merge local pull request branches
  package-lock.json
  package.json
  src/cli/invocation/command/addCommandsByName.ts
  src/cli/invocation/command/addGitHooksCommands.ts
  src/cli/invocation/command/addIntentsAsCommands.ts
  src/cli/invocation/command/support/embeddedCommandExecution.ts
  src/cli/invocation/command/support/runCommandOnColocatedAutomationClient.ts
  src/cli/invocation/git/triggerGitEvents.ts
  src/common/git/handlePushBasedEventOnRepo.ts
  src/sdm/binding/project/ExpandedTreeRepoRefResolver.ts
  src/sdm/binding/project/FileSystemProjectLoader.ts
  src/sdm/binding/project/FileSystemRemoteRepoRef.ts
  src/sdm/binding/project/LocalRepoTargets.ts
  src/sdm/binding/project/expandedTreeRepoFinder.ts
  src/sdm/binding/project/fileSystemProjectPersister.ts
  src/sdm/configuration/defaultLocalSoftwareDeliveryMachineConfiguration.ts
Labels: auto-merge:on-approve, changelog:added
