Repository atomist/sdm-local, pull requests merged in 2019-04, with the labels that each got.

#247 Suggest starting feed only if relevant
  lib/cli/invocation/command/addReplayCommand.ts
  lib/cli/invocation/git/runOnGitHook.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:changed

#253 Fix FileSystemRemoteRepoRef branch implementation
  lib/cli/invocation/http/invokeEventHandlerUsingHttp.ts
  lib/sdm/binding/project/FileSystemRemoteRepoRef.ts
  lib/sdm/invocation/invokeEventHandlerInProcess.ts
  package-lock.json
  package.json
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:fixed

#249 Remove the message about channels
  docs/onStartListener.md
  lib/cli/invocation/command/addBootstrapCommands.ts
Labels: auto-merge-method:squash, auto-merge:on-check-success, changelog:removed, enhancement

#256 Remove stray dependency on types/open
  package.json
Labels: auto-merge:on-approve, changelog:removed, enhancement

#259 Remove excess slash from directory
  lib/cli/invocation/command/addBootstrapCommands.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, bug, changelog:fixed
